### ISSUE TITLE
Message body cant be cleaned

### ISSUE THREAD

**Issue by HEMA-MATHAVAN** [nicbet/MailboxMiner#2]
hi nicolas
I tried to clean the message body with the following command.

```
#Cleaning message body
    java -Xmx1024M -jar /home/hema/MailboxMiner-mvn-build/MailboxMiner2/target/mailboxmina2-0.0.1-SNAPSHOT.jar -connection //localhost:5432/test_db -username hema -password PASSWORD -module clean -debug -logfile test-clean.log -verbosity 3 -path PATH/TO/FILE
```

 The field **body_text_cleaned_text** of the **bodies table** is empty.

It seems that the clean module doesnt contain any implementation or it seems missing.

**Comment by nicbet** [comment]
You are right - the clean module has an empty implementation. We were in the middle of porting this piece from the first MailboxMiner prototype when we dropped the project.

The original implementation looked like this:

```
/**
     * Retrieve a cleaned (no quotes, mimes, XY wrote on:)
     * @return a cleaned body text
     */
    public String getCleanedBody() {
        String cleanedBody = this.body;
        String inLines = cleanedBody.replaceAll("(?m)(^>.*?$)", ""); //remove all inline replies
        String reHeader = inLines.replaceAll("(?m)^On.+ wrote:$", ""); // remove "on... wrote:" lines
        String rePGP = reHeader.replaceAll("(?m)(?s)(-+BEGIN PGP SIGNATURE-+)(.*?)(-+END PGP SIGNATURE-+)", ""); // remove PGP signatures
        String reAtt = rePGP.replaceAll("(?m)(?s)(--=-([a-zA-Z0-9\\+\\/]+)(-{2})?)(.*?)(--=-([a-zA-Z0-9\\+\\/]+)(-{2})?)", ""); //remove the attachments    
        cleanedBody = reAtt.replaceAll("(?m)^Content-.*", "");
        cleanedBody = attRemove.replaceAll("(?m)(^>.*?$)", "");
        return cleanedBody;
    }

    //cleans the body but leaves in the replies
    public String getCleanedBodyWithQuotes() {
        String inLines = this.body;
        String inLines = cleanedBody.replaceAll("(?m)(^>.*?$)", ""); //remove all inline replies
        String reHeader = inLines.replaceAll("(?m)^On.+ wrote:$", ""); // remove "on... wrote:" lines
        String rePGP = reHeader.replaceAll("(?m)(?s)(-+BEGIN PGP SIGNATURE-+)(.*?)(-+END PGP SIGNATURE-+)", ""); // remove PGP signatures
        String reAtt = rePGP.replaceAll("(?m)(?s)(--=-([a-zA-Z0-9\\+\\/]+)(-{2})?)(.*?)(--=-([a-zA-Z0-9\\+\\/]+)(-{2})?)", ""); //remove the attachments    
        String cleanedBody = reAtt.replaceAll("(?m)^Content-.*", "");
        return cleanedBody;
    }
```

If you want to play around with this code and send a pull request - that'd be fantastic. ;-)

**Comment by HEMA-MATHAVAN** [comment]
Hi nicolas,

i am not a java guy. so i wont be able to push modifications effectively.i came across these papers using mailboxminer in their research.
- An Empirical Study of Build System Migrations in Practice:
  Case Studies on KDE and the Linux Kernel
- The Evolution of the R Software Ecosystem
- Management of community contributions
  A case study on the Android and Linux software ecosystems(by u) 

I am currently working on a research project which aims at mining natural language artifacts. i am completely into nlp and and python. i wanted to use the mailboxminer tool to perform the necessary preprocessing (splitting,duplicate detection,cleaning,thread structure,personalities identification). 

I think the above said papers where using mailboxminer(prototype) and not mailboxminer2. where can i download your old tool?
I would like to use your tool and cite it in my research paper.

**Comment by nicbet** [comment]
Hi Hema, thanks for your note. The original code used to be on https://code.google.com/archive/p/mailboxminer/ which appears to have been discontinued. This repository is the one I am maintaining. The tool contained herein should be helpful for the preprocessing tasks you mentioned - why don't you give it a try?

Best, NB.
